### ISSUE TITLE
LV pro non responsive

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#147] opened 2022-11-11 00:30 UTC
Clicking on the Z position setting several times to get it to let me change it, it went gray and is unresponsive
[LumaViewProApp-ESW.zip](https://github.com/EtalumaSupport/LumaViewPro/files/9985495/LumaViewProApp-ESW.zip)
.  Here are the logs.

**Comment by iwaniec** [comment] 2022-11-14 04:27
This issue is caused by issue #152 . Will close this to consolidate issues.

**Closed by iwaniec** 2022-11-14 04:27 UTC
