### ISSUE TITLE
Protocol - Deleting steps past step 0 causes crash.

### ISSUE THREAD

**Issue by kmcleaster** [EtalumaSupport/LumaViewPro#179] opened 2023-02-08 22:13 UTC
Clicling on Change for a single step protocol also causes a crash

**Comment by iwaniec** [comment] 2023-02-14 00:45
Cannot reproduce. Please test and if no longer failing, close the issue.

**Comment by kmcleaster** [comment] 2023-02-16 22:48
Clicking Delete on the final step is now causing a crash. It seems that the last step is in the center of the stage.

**Comment by iwaniec** [comment] 2023-03-24 03:47
Should be fixed. Please reopen if problem persists.

**Closed by iwaniec** 2023-03-24 03:47 UTC
Labels: bug
